---
default_set: 'ubuntu-server-12042-x64'
sets:
  'ubuntu-server-12042-x64':
    nodes:
      "main":
        prefab: 'ubuntu-server-12042-x64'
  'centos-65-x64':
    nodes:
      'main':
        prefab: 'centos-65-x64'
