---
'centos-65-x64':
  description: ""
  facts:
    kernelrelease: "2.6.32-358.el6.x86_64"
    operatingsystem: CentOS
    kernelmajversion: "2.6"
    architecture: x86_64
    facterversion: "1.6.18"
    kernelversion: "2.6.32"
    operatingsystemrelease: "6.5"
    osfamily: RedHat
    lsbmajdistrelease: "6"
    lsbdistcodename: Final
    lsbdistdescription: "CentOS release 6.5 (Final)"
    lsbdistid: CentOS
    lsbdistrelease: "6.5"
    kernel: Linux
    rubyversion: "1.8.7"
  provider_specifics:
    vagrant_virtualbox:
      box: 'centos-65-x64-nocm'
      box_url: 'http://puppet-vagrant-boxes.puppetlabs.com/centos-65-x64-virtualbox-nocm.box'
