language: ruby
script: "bundle exec rake spec SPEC_OPTS='--format documentation'"
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - ruby-head
env:
  - PUPPET_GEM_VERSION="~> 2.6"
  - PUPPET_GEM_VERSION="~> 2.7"
  - PUPPET_GEM_VERSION="~> 3.0"
  - PUPPET_GEM_VERSION="~> 3.1"
  - PUPPET_GEM_VERSION="> 3.1"
matrix:
  allow_failures:
    - rvm: 2.0.0
    - rvm: ruby-head
  exclude:
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.1"
    - rvm: ruby-head
      env: PUPPET_GEM_VERSION="~> 3.1"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.0"
    - rvm: ruby-head
      env: PUPPET_GEM_VERSION="~> 3.0"
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 2.7"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 2.7"
    - rvm: ruby-head
      env: PUPPET_GEM_VERSION="~> 2.7"
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 2.6"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 2.6"
    - rvm: ruby-head
      env: PUPPET_GEM_VERSION="~> 2.6"
notifications:
  email: false
