name 'thbe-ovirt'
version '0.1.0'

author 'Thomas Bendler <project@bendler-net.de>'
license 'GPLv3'
project_page 'https://github.com/thbe/puppet-ovirt.git'
source 'https://github.com/thbe/puppet-ovirt.git'
summary 'oVirt management module'
description 'oVirt management module'
dependency 'thbe/yum', '>=0.3.0'
