fixtures:
  repositories:
    "keystone": "git://github.com/stackforge/puppet-keystone.git"
    "cinder": "git://github.com/stackforge/puppet-cinder.git"
    "mysql": "git://github.com/puppetlabs/puppetlabs-mysql.git"
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "sysctl": "git://github.com/duritong/puppet-sysctl.git"
    "rabbitmq": "git://github.com/puppetlabs/puppetlabs-rabbitmq.git"
    "qpid": "git://github.com/dprince/puppet-qpid.git"
    'inifile':  'git://github.com/cprice-puppet/puppetlabs-inifile'
    "postgresql": "git://github.com/puppetlabs/puppet-postgresql.git"
  symlinks:
    "nova": "#{source_dir}"
