fixtures:
  repositories:
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib"
    "concat": "git://github.com/puppetlabs/puppetlabs-concat"
  symlinks:
    "puppet": "#{source_dir}"
    "wr": "#{source_dir}/../wr"
