#!/bin/sh
# e2croncheck – run e2fsck on a snapshot of an LVM volume
#
# USAGE: e2croncheck vgname/lvname
# Call this with >/dev/null from your weekly crontab.
#
# The script prints nothing to stderr and returns zero if the check is
# successful. Otherwise, the fsck log is printed to stderr and a non-zero value
# is returned. The cron daemon will then mail the output to you.
#
# Written by Theodore Ts'o, Copyright 2007-2008
# Modified by Johan Kiviniemi
#
# This file may be redistributed under the terms of the GNU Public License,
# version 2.

set -e

#add ability to delay check for up to one week
delay=/var/tmp/e2croncheck_delay
one_week=604800 #7 * 24 * 60 * 60
if [ -f "$delay" ]; then
    now=$(date +%s)
    delay_age=$(($now - $(stat -c '%Y' "$delay")))
    if [ "$delay_age" -lt "$one_week" ]; then
        >&2 echo "e2croncheck has been delayed"
        false
    fi
fi

if [ "$#" -ne 1 ]; then
  >&2 printf "USAGE: %s vg/lv\n" "$0"
  false
fi

snapsize=500G
fsckopts="-ttv -C0"

fscklog="$(mktemp -t e2fsck.log.XXXXXXXXXX)"
traps='rm -f "$fscklog"'
trap "$traps" 0

vg_lv="$1"; shift

vg="${vg_lv%%/*}"
lv="${vg_lv#*/}"

if [ "$vg_lv" != "$vg/$lv" ] || [ -z "$vg" ] || [ -z "$lv" ]; then
  >&2 printf "%s: Invalid vg/lv\n" "$vg_lv"
  false
fi

lv_snap="$lv-fsck-snapshot"

dev="/dev/$vg/$lv"
dev_snap="/dev/$vg/$lv_snap"

start_timestamp=$(date --rfc-3339=ns)
echo "Background fsck started at $start_timestamp"

#experiment with larger chunksize that matches RAID chunksize
lvcreate --snapshot --chunksize 64 --size "$snapsize" --name "$lv_snap" "$vg/$lv"
traps="$traps"'; lvremove -f "$vg/$lv_snap"'
trap "$traps" 0

if nice ionice -c 3 logsave -as "$fscklog" e2fsck -p  $fsckopts "$dev_snap" && \
   nice ionice -c 3 logsave -as "$fscklog" e2fsck -fy $fsckopts "$dev_snap"; then
  end_timestamp=$(date --rfc-3339=ns)
  printf "%s: Background fsck succeeded at %s\n" "$vg/$lv" "$end_timestamp"

else
  >&2 printf "%s: Background fsck failed! Reboot to fsck soon!\n" "$vg/$lv"

  >&2 cat "$fscklog"

  false
fi

# vim:set et sw=2 sts=2:
